profiles:
  default:
    duration: 4w
    pass_threshold: 66
    periodic_status_check: "1 week"
    allowed_voters:
      teams:
        - cncf-toc-voters
      exclude_team_maintainers: true
    close_on_passing: true
